<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERPLAB.DataAccess\ERPLAB.DataAccess.csproj" />
    <ProjectReference Include="..\ERPLAB.Models\ERPLAB.Models.csproj" />
  </ItemGroup>

</Project>
